package com.lizard.eye.model;

public class Model {

	public String TIME_TAKEN = "TIME_TAKEN";

	public String COLOR_SEARCH_LIST = "COLOR_SEARCH_LIST";

	private static Model sSingleton;

	public static Model getSingleton() {
		if (sSingleton == null) {
			sSingleton = new Model();
		}
		return sSingleton;
	}

	public String SHARED_PREFS = "com.lizard.eyes.USER_PREF"; // pref file\

	public String FLURRY_API_KEY = "NYVBGRBKYP99Y2XC3WG9";


	public String SelectedItemId = "SelectedItemId";

	public String SelectedItemName = "SelectedItemName";

	public String SelectedItemLength = "SelectedItemLength";

	public String SearchCount = "SearchCount";


	public String MAXIMUM_LEVELS = "5";

	public String EACH_LEVEL_ITEMS = "10";

	/** NO OF ICONS **/

	public String AZTECH_ICONS = "20";
	
	public String BALL_ICONS = "20";

	public String BRUCE_ICONS = "20";//21

	public String CHRIST_ICONS = "20";

	public String MEXICO_ICONS = "20";

	public String MONEY_ICONS = "20";

	public String MYTH_ICONS = "20";

	public String ROBO_ICONS = "20";
	
	public String SPORTS_ICONS = "20";

	public String STICK_ICONS = "20";

	public String TREE_ICONS = "20";

	//public String ZODIAC_ICONS = "12";

	public String PLAY_LEVEL = "PLAY_TLEVEL";
	
	/** END OF NO OF ICONS **/
	/** COMPLETED LEVELS **/

	public String AZTECH_COMPLETED_LEVEL = "AZTECH_COMPLETED_LEVEL";// 1

	public String BALL_COMPLETED_LEVEL = "BALL_COMPLETED_LEVEL";//2
	
	public String BRUCE_COMPLETED_LEVEL = "BRUCE_COMPLETED_LEVEL";// 3

	public String CHRIST_COMPLETED_LEVEL = "CHRIST_COMPLETED_LEVEL";// 4

	public String MEXICO_COMPLETED_LEVEL = "MEXICAN_COMPLETED_LEVEL";// 5

	public String MONEY_COMPLETED_LEVEL = "MONEY_COMPLETED_LEVEL";// 6

	public String MYTH_COMPLETED_LEVEL = "MYTH_COMPLETED_LEVEL";// 7

	public String ROBO_COMPLETED_LEVEL = "ROBO_COMPLETED_LEVEL";// 8
	
	public String SPORTS_COMPLETED_LEVEL = "SPORTS_COMPLETED_LEVEL";//9

	public String STICK_COMPLETED_LEVEL = "STICK_COMPLETED_LEVEL";//10

	public String TREE_COMPLETED_LEVEL = "TREE_COMPLETED_LEVEL";// 11

	//public String ZODIAC_COMPLETED_LEVEL = "ZODIAC_COMPLETED_LEVEL";// 12
	
	public String TIME_SHAPE_COMPLETED_LEVEL = "TIME_SHAPE_COMPLETED_LEVEL";//1

	/** END OF COMPLETED LEVELS **/

	public String COMPLETED_LEVEL = "COMPLETED_LEVEL";


	public String base64EncodedPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoiG2s0VZPD9rYsA9UosVFotcoL14kxsfaMIhDeQMHlJJhLBa6P8PWGpBSi/qjFbTf2PNY3+n9UUpwJ5tEmtk3SllshwUkkjEjBaAmtYd5M24YYHMpbKc9BE1KqAVFeexBm9FMGUgJ0oW7Gc3WXS6pOlKR0mV0mGlEMPyHicF36D5NlvxNj6k6b2D05YfPdBPrtCQ2OLH1jzUh06b/ISh18qnsP108qMH8nE/9MuFq0BrDdbjiqLRwKRd1wFO58v7ry3g907Q/sM82WMxvSe8TtXIXALj/6SEtSb2Fxzn78CDoi4xay5eNoYrMLdCqKU+L5nsDHntLAJuaamqqWxXkwIDAQAB";
										
	public String SKU_PREMIUM_ALL = "lizard_eye.12";

	
	public String premiumVersion = "premiumVersion";

	public int RC_REQUEST = 10001;


	/** World Mode **/
	public String WORLD_MODE_TOTAL_ATTEMPTS = "WORLD_MODE_TOTAL_ATTEMPTS";
	
	public String WORLD_MODE_POINTS_WON = "WORLD_MODE_POINTS_WON";
	
	public String WORLD_MODE_TOTAL_ANSWERS = "WORLD_MODE_TOTAL_ANSWERS";



	/**End of World Mode**/
	/**TIME MODE**/
	
	public String TIME_MODE_LEVEL = "TIME_MODE_LEVEL";
	
	public String TIME_MODE_TOTAL_ATTEMPTS = "TIME_MODE_TOTAL_ATTEMPTS";
	
	public String TIME_MODE_TOTAL_ANSWERS = "TIME_MODE_TOTAL_ANSWERS";
	
	public String TIME_MODE_TOTAL_AVERAGE_TIME = "TIME_MODE_TOTAL_AVERAGE_TIME";

	public String TIME_MODE_CORRECT_ANSWER_AVERAGE_TIME = "TIME_MODE_CORRECT_ANSWER_AVERAGE_TIME";

	public String TIME_MODE_POINTS_WON = "TIME_MODE_POINTS_WON";
	
	/**END OF TIME MODE**/

	/** AZTECH LEVEL SCRORES **/

	public String AZTECH_FIRST_LEVEL_ANSWERS = "AZTECH_FIRST_LEVEL_ANSWERS";

	public String AZTECH_SECOND_LEVEL_ANSWERS = "AZTECH_SECOND_LEVEL_ANSWERS";

	public String AZTECH_THIRD_LEVEL_ANSWERS = "AZTECH_THIRD_LEVEL_ANSWERS";

	public String AZTECH_FOURTH_LEVEL_ANSWERS = "AZTECH_THIRD_LEVEL_ANSWERS";

	public String AZTECH_FIFTH_LEVEL_ANSWERS = "AZTECH_FIFTH_LEVEL_ANSWERS";

	public String AZTECH_FIRST_LEVEL_ATTEMPTS = "AZTECH_FIRST_LEVEL_ATTEMPTS";

	public String AZTECH_SECOND_LEVEL_ATTEMPTS = "AZTECH_SECOND_LEVEL_ATTEMPTS";

	public String AZTECH_THIRD_LEVEL_ATTEMPTS = "AZTECH_THIRD_LEVEL_ATTEMPTS";

	public String AZTECH_FOURTH_LEVEL_ATTEMPTS = "AZTECH_THIRD_LEVEL_ATTEMPTS";

	public String AZTECH_FIFTH_LEVEL_ATTEMPTS = "AZTECH_FIFTH_LEVEL_ATTEMPTS";

	/** END OF AZTECH LEVEL SCRORES **/
	
	/** BALL LEVEL SCRORES **/

	public String BALL_FIRST_LEVEL_ANSWERS = "BALL_FIRST_LEVEL_ANSWERS";

	public String BALL_SECOND_LEVEL_ANSWERS = "BALL_SECOND_LEVEL_ANSWERS";

	public String BALL_THIRD_LEVEL_ANSWERS = "BALL_THIRD_LEVEL_ANSWERS";

	public String BALL_FOURTH_LEVEL_ANSWERS = "BALL_THIRD_LEVEL_ANSWERS";

	public String BALL_FIFTH_LEVEL_ANSWERS = "BALL_FIFTH_LEVEL_ANSWERS";

	public String BALL_FIRST_LEVEL_ATTEMPTS = "BALL_FIRST_LEVEL_ATTEMPTS";

	public String BALL_SECOND_LEVEL_ATTEMPTS = "BALL_SECOND_LEVEL_ATTEMPTS";

	public String BALL_THIRD_LEVEL_ATTEMPTS = "BALL_THIRD_LEVEL_ATTEMPTS";

	public String BALL_FOURTH_LEVEL_ATTEMPTS = "BALL_THIRD_LEVEL_ATTEMPTS";

	public String BALL_FIFTH_LEVEL_ATTEMPTS = "BALL_FIFTH_LEVEL_ATTEMPTS";

	/** END OF BALL LEVEL SCRORES **/

	/** BBRUCE LEVEL SCRORES **/

	public String BRUCE_FIRST_LEVEL_ANSWERS = "BRUCE_FIRST_LEVEL_ANSWERS";

	public String BRUCE_SECOND_LEVEL_ANSWERS = "BRUCE_SECOND_LEVEL_ANSWERS";

	public String BRUCE_THIRD_LEVEL_ANSWERS = "BRUCE_THIRD_LEVEL_ANSWERS";

	public String BRUCE_FOURTH_LEVEL_ANSWERS = "BRUCE_THIRD_LEVEL_ANSWERS";

	public String BRUCE_FIFTH_LEVEL_ANSWERS = "BRUCE_FIFTH_LEVEL_ANSWERS";

	public String BRUCE_FIRST_LEVEL_ATTEMPTS = "BRUCE_FIRST_LEVEL_ATTEMPTS";

	public String BRUCE_SECOND_LEVEL_ATTEMPTS = "BRUCE_SECOND_LEVEL_ATTEMPTS";

	public String BRUCE_THIRD_LEVEL_ATTEMPTS = "BRUCE_THIRD_LEVEL_ATTEMPTS";

	public String BRUCE_FOURTH_LEVEL_ATTEMPTS = "BRUCE_THIRD_LEVEL_ATTEMPTS";

	public String BRUCE_FIFTH_LEVEL_ATTEMPTS = "BRUCE_FIFTH_LEVEL_ATTEMPTS";

	/** END OF BRUCE LEVEL SCRORES **/

	/** CHRIST LEVEL SCRORES **/

	public String CHRIST_FIRST_LEVEL_ANSWERS = "CHRIST_FIRST_LEVEL_ANSWERS";

	public String CHRIST_SECOND_LEVEL_ANSWERS = "CHRIST_SECOND_LEVEL_ANSWERS";

	public String CHRIST_THIRD_LEVEL_ANSWERS = "CHRIST_THIRD_LEVEL_ANSWERS";

	public String CHRIST_FOURTH_LEVEL_ANSWERS = "CHRIST_THIRD_LEVEL_ANSWERS";

	public String CHRIST_FIFTH_LEVEL_ANSWERS = "CHRIST_FIFTH_LEVEL_ANSWERS";

	public String CHRIST_FIRST_LEVEL_ATTEMPTS = "CHRIST_FIRST_LEVEL_ATTEMPTS";

	public String CHRIST_SECOND_LEVEL_ATTEMPTS = "CHRIST_SECOND_LEVEL_ATTEMPTS";

	public String CHRIST_THIRD_LEVEL_ATTEMPTS = "CHRIST_THIRD_LEVEL_ATTEMPTS";

	public String CHRIST_FOURTH_LEVEL_ATTEMPTS = "CHRIST_THIRD_LEVEL_ATTEMPTS";

	public String CHRIST_FIFTH_LEVEL_ATTEMPTS = "CHRIST_FIFTH_LEVEL_ATTEMPTS";

	/** END OF CHRIST LEVEL SCRORES **/

	/** MONEY LEVEL SCRORES **/

	public String MONEY_FIRST_LEVEL_ANSWERS = "MONEY_FIRST_LEVEL_ANSWERS";

	public String MONEY_SECOND_LEVEL_ANSWERS = "MONEY_SECOND_LEVEL_ANSWERS";

	public String MONEY_THIRD_LEVEL_ANSWERS = "MONEY_THIRD_LEVEL_ANSWERS";

	public String MONEY_FOURTH_LEVEL_ANSWERS = "MONEY_THIRD_LEVEL_ANSWERS";

	public String MONEY_FIFTH_LEVEL_ANSWERS = "MONEY_FIFTH_LEVEL_ANSWERS";

	public String MONEY_FIRST_LEVEL_ATTEMPTS = "MONEY_FIRST_LEVEL_ATTEMPTS";

	public String MONEY_SECOND_LEVEL_ATTEMPTS = "MONEY_SECOND_LEVEL_ATTEMPTS";

	public String MONEY_THIRD_LEVEL_ATTEMPTS = "MONEY_THIRD_LEVEL_ATTEMPTS";

	public String MONEY_FOURTH_LEVEL_ATTEMPTS = "MONEY_THIRD_LEVEL_ATTEMPTS";

	public String MONEY_FIFTH_LEVEL_ATTEMPTS = "MONEY_FIFTH_LEVEL_ATTEMPTS";
	/** END OF MONEY LEVEL SCRORES **/

	/** MYTHOLOGICAL LEVEL SCRORES **/

	public String MYTH_FIRST_LEVEL_ANSWERS = "MYTH_FIRST_LEVEL_ANSWERS";

	public String MYTH_SECOND_LEVEL_ANSWERS = "MYTH_SECOND_LEVEL_ANSWERS";

	public String MYTH_THIRD_LEVEL_ANSWERS = "MYTH_THIRD_LEVEL_ANSWERS";

	public String MYTH_FOURTH_LEVEL_ANSWERS = "MYTH_THIRD_LEVEL_ANSWERS";

	public String MYTH_FIFTH_LEVEL_ANSWERS = "MYTH_FIFTH_LEVEL_ANSWERS";

	public String MYTH_FIRST_LEVEL_ATTEMPTS = "MYTH_FIRST_LEVEL_ATTEMPTS";

	public String MYTH_SECOND_LEVEL_ATTEMPTS = "MYTH_SECOND_LEVEL_ATTEMPTS";

	public String MYTH_THIRD_LEVEL_ATTEMPTS = "MYTH_THIRD_LEVEL_ATTEMPTS";

	public String MYTH_FOURTH_LEVEL_ATTEMPTS = "MYTH_THIRD_LEVEL_ATTEMPTS";

	public String MYTH_FIFTH_LEVEL_ATTEMPTS = "MYTH_FIFTH_LEVEL_ATTEMPTS";

	/** END OF MYTHOLOGICAL LEVEL SCRORES **/

	/** MEXICO LEVEL SCRORES **/

	public String MEXICO_FIRST_LEVEL_ANSWERS = "MEXICO_FIRST_LEVEL_ANSWERS";

	public String MEXICO_SECOND_LEVEL_ANSWERS = "MEXICO_SECOND_LEVEL_ANSWERS";

	public String MEXICO_THIRD_LEVEL_ANSWERS = "MEXICO_THIRD_LEVEL_ANSWERS";

	public String MEXICO_FOURTH_LEVEL_ANSWERS = "MEXICO_THIRD_LEVEL_ANSWERS";

	public String MEXICO_FIFTH_LEVEL_ANSWERS = "MEXICO_FIFTH_LEVEL_ANSWERS";

	public String MEXICO_FIRST_LEVEL_ATTEMPTS = "MEXICO_FIRST_LEVEL_ATTEMPTS";

	public String MEXICO_SECOND_LEVEL_ATTEMPTS = "MEXICO_SECOND_LEVEL_ATTEMPTS";

	public String MEXICO_THIRD_LEVEL_ATTEMPTS = "MEXICO_THIRD_LEVEL_ATTEMPTS";

	public String MEXICO_FOURTH_LEVEL_ATTEMPTS = "MEXICO_THIRD_LEVEL_ATTEMPTS";

	public String MEXICO_FIFTH_LEVEL_ATTEMPTS = "BRUCE_FIFTH_LEVEL_ATTEMPTS";

	/** END OF MEXICO LEVEL SCRORES **/

	/** END OF ROBO LEVEL SCRORES **/

	public String ROBO_FIRST_LEVEL_ANSWERS = "ROBO_FIRST_LEVEL_ANSWERS";

	public String ROBO_SECOND_LEVEL_ANSWERS = "ROBO_SECOND_LEVEL_ANSWERS";

	public String ROBO_THIRD_LEVEL_ANSWERS = "ROBO_THIRD_LEVEL_ANSWERS";

	public String ROBO_FOURTH_LEVEL_ANSWERS = "ROBO_THIRD_LEVEL_ANSWERS";

	public String ROBO_FIFTH_LEVEL_ANSWERS = "ROBO_FIFTH_LEVEL_ANSWERS";

	public String ROBO_FIRST_LEVEL_ATTEMPTS = "ROBO_FIRST_LEVEL_ATTEMPTS";

	public String ROBO_SECOND_LEVEL_ATTEMPTS = "ROBO_SECOND_LEVEL_ATTEMPTS";

	public String ROBO_THIRD_LEVEL_ATTEMPTS = "ROBO_THIRD_LEVEL_ATTEMPTS";

	public String ROBO_FOURTH_LEVEL_ATTEMPTS = "ROBO_THIRD_LEVEL_ATTEMPTS";

	public String ROBO_FIFTH_LEVEL_ATTEMPTS = "ROBO_FIFTH_LEVEL_ATTEMPTS";

	/** END OF ROBO LEVEL SCRORES **/
	
	
	/** SPORTS LEVEL SCRORES **/

	public String SPORTS_FIRST_LEVEL_ANSWERS = "SPORTS_FIRST_LEVEL_ANSWERS";

	public String SPORTS_SECOND_LEVEL_ANSWERS = "SPORTS_SECOND_LEVEL_ANSWERS";

	public String SPORTS_THIRD_LEVEL_ANSWERS = "SPORTS_THIRD_LEVEL_ANSWERS";

	public String SPORTS_FOURTH_LEVEL_ANSWERS = "SPORTS_THIRD_LEVEL_ANSWERS";

	public String SPORTS_FIFTH_LEVEL_ANSWERS = "SPORTS_FIFTH_LEVEL_ANSWERS";

	public String SPORTS_FIRST_LEVEL_ATTEMPTS = "SPORTS_FIRST_LEVEL_ATTEMPTS";

	public String SPORTS_SECOND_LEVEL_ATTEMPTS = "SPORTS_SECOND_LEVEL_ATTEMPTS";

	public String SPORTS_THIRD_LEVEL_ATTEMPTS = "SPORTS_THIRD_LEVEL_ATTEMPTS";

	public String SPORTS_FOURTH_LEVEL_ATTEMPTS = "SPORTS_THIRD_LEVEL_ATTEMPTS";

	public String SPORTS_FIFTH_LEVEL_ATTEMPTS = "SPORTS_FIFTH_LEVEL_ATTEMPTS";

	/** END OF SPORTS LEVEL SCRORES **/
	
	
	/** STICK LEVEL SCRORES **/

	public String STICK_FIRST_LEVEL_ANSWERS = "STICK_FIRST_LEVEL_ANSWERS";

	public String STICK_SECOND_LEVEL_ANSWERS = "STICK_SECOND_LEVEL_ANSWERS";

	public String STICK_THIRD_LEVEL_ANSWERS = "STICK_THIRD_LEVEL_ANSWERS";

	public String STICK_FOURTH_LEVEL_ANSWERS = "STICK_THIRD_LEVEL_ANSWERS";

	public String STICK_FIFTH_LEVEL_ANSWERS = "STICK_FIFTH_LEVEL_ANSWERS";

	public String STICK_FIRST_LEVEL_ATTEMPTS = "STICK_FIRST_LEVEL_ATTEMPTS";

	public String STICK_SECOND_LEVEL_ATTEMPTS = "STICK_SECOND_LEVEL_ATTEMPTS";

	public String STICK_THIRD_LEVEL_ATTEMPTS = "STICK_THIRD_LEVEL_ATTEMPTS";

	public String STICK_FOURTH_LEVEL_ATTEMPTS = "STICK_THIRD_LEVEL_ATTEMPTS";

	public String STICK_FIFTH_LEVEL_ATTEMPTS = "STICK_FIFTH_LEVEL_ATTEMPTS";

	/** END OF STICK LEVEL SCRORES **/
	

	/** TREE LEVEL SCRORES **/

	public String TREE_FIRST_LEVEL_ANSWERS = "TREE_FIRST_LEVEL_ANSWERS";

	public String TREE_SECOND_LEVEL_ANSWERS = "TREE_SECOND_LEVEL_ANSWERS";

	public String TREE_THIRD_LEVEL_ANSWERS = "TREE_THIRD_LEVEL_ANSWERS";

	public String TREE_FOURTH_LEVEL_ANSWERS = "TREE_THIRD_LEVEL_ANSWERS";

	public String TREE_FIFTH_LEVEL_ANSWERS = "TREE_FIFTH_LEVEL_ANSWERS";

	public String TREE_FIRST_LEVEL_ATTEMPTS = "TREE_FIRST_LEVEL_ATTEMPTS";

	public String TREE_SECOND_LEVEL_ATTEMPTS = "TREE_SECOND_LEVEL_ATTEMPTS";

	public String TREE_THIRD_LEVEL_ATTEMPTS = "TREE_THIRD_LEVEL_ATTEMPTS";

	public String TREE_FOURTH_LEVEL_ATTEMPTS = "TREE_THIRD_LEVEL_ATTEMPTS";

	public String TREE_FIFTH_LEVEL_ATTEMPTS = "TREE_FIFTH_LEVEL_ATTEMPTS";

	/** END OF TREE LEVEL SCRORES **/



	/** ZODIAC LEVEL SCRORES **/

//	public String ZODIAC_FIRST_LEVEL_ANSWERS = "ZODIAC_FIRST_LEVEL_ANSWERS";
//
//	public String ZODIAC_SECOND_LEVEL_ANSWERS = "ZODIAC_SECOND_LEVEL_ANSWERS";
//
//	public String ZODIAC_THIRD_LEVEL_ANSWERS = "ZODIAC_THIRD_LEVEL_ANSWERS";
//
//	public String ZODIAC_FOURTH_LEVEL_ANSWERS = "ZODIAC_THIRD_LEVEL_ANSWERS";
//
//	public String ZODIAC_FIFTH_LEVEL_ANSWERS = "ZODIAC_FIFTH_LEVEL_ANSWERS";
//
//	public String ZODIAC_FIRST_LEVEL_ATTEMPTS = "ZODIAC_FIRST_LEVEL_ATTEMPTS";
//
//	public String ZODIAC_SECOND_LEVEL_ATTEMPTS = "ZODIAC_SECOND_LEVEL_ATTEMPTS";
//
//	public String ZODIAC_THIRD_LEVEL_ATTEMPTS = "ZODIAC_THIRD_LEVEL_ATTEMPTS";
//
//	public String ZODIAC_FOURTH_LEVEL_ATTEMPTS = "ZODIAC_THIRD_LEVEL_ATTEMPTS";
//
//	public String ZODIAC_FIFTH_LEVEL_ATTEMPTS = "ZODIAC_FIFTH_LEVEL_ATTEMPTS";

	/** END OF ZODIAC LEVEL SCRORES **/

	/** Points Related Stuff **/

	public int POINTS_PER_ANSWER = 100;

	public int POINTS_FIRST_LEVEL_ANSWER = 1 * POINTS_PER_ANSWER;

	public int POINTS_SECOND_LEVEL_ANSWER = 2 * POINTS_PER_ANSWER;

	public int POINTS_THIRD_LEVEL_ANSWER = 3 * POINTS_PER_ANSWER;

	public int POINTS_FOURTH_LEVEL_ANSWER = 4 * POINTS_PER_ANSWER;

	public int POINTS_FIFTH_LEVEL_ANSWER = 5 * POINTS_PER_ANSWER;

	public String POINTS_WON="POINTS_WON";
	/** End of Points Related Stuff **/

	/** Relax Mode **/

	public String RELAX_MODE_LEVEL = "RELAX_MODE_LEVEL";

	public int RELAX_NO_MODES = 11;

	public String RELAX_MODE_WORLD = "RELAX_MODE_WORLD";
	
	public String RELAX_MODE_ATTEMPTS = "RELAX_MODE_ATTEMPTS";
	
	public String RELAX_MODE_ANSWERS = "RELAX_MODE_ANSWERS";

	/** Relax Mode Level **/
	
	/**Timer**/
	
	
	public int TIME_SECOND_UPDATE = 1000;
	/**End of Timer**/
	
	
	/** TIME LEVEL SCRORES **/

	public String TIME_SHAPE_FIRST_LEVEL_ANSWERS = "TIME_SHAPE_FIRST_LEVEL_ANSWERS";

	public String TIME_SHAPE_SECOND_LEVEL_ANSWERS = "TIME_SHAPE_SECOND_LEVEL_ANSWERS";

	public String TIME_SHAPE_THIRD_LEVEL_ANSWERS = "TIME_SHAPE_THIRD_LEVEL_ANSWERS";

	public String TIME_SHAPE_FOURTH_LEVEL_ANSWERS = "TIME_SHAPE_THIRD_LEVEL_ANSWERS";

	public String TIME_SHAPE_FIFTH_LEVEL_ANSWERS = "TIME_SHAPE_FIFTH_LEVEL_ANSWERS";

	public String TIME_SHAPE_FIRST_LEVEL_ATTEMPTS = "TIME_SHAPE_FIRST_LEVEL_ATTEMPTS";

	public String TIME_SHAPE_SECOND_LEVEL_ATTEMPTS = "TIME_SHAPE_SECOND_LEVEL_ATTEMPTS";

	public String TIME_SHAPE_THIRD_LEVEL_ATTEMPTS = "TIME_SHAPE_THIRD_LEVEL_ATTEMPTS";

	public String TIME_SHAPE_FOURTH_LEVEL_ATTEMPTS = "TIME_SHAPE_THIRD_LEVEL_ATTEMPTS";

	public String TIME_SHAPE_FIFTH_LEVEL_ATTEMPTS = "TIME_FIFTH_LEVEL_ATTEMPTS";

	/** END OF TIME LEVEL SCRORES **/
	

}
